services:
  anvil:
    container_name: structuracontractus_anvil
    entrypoint: anvil --block-time 1 --block-base-fee-per-gas 0 --gas-limit 3000000000 --hardfork cancun --host 0.0.0.0 --port 8545
    healthcheck:
      test: [ "CMD-SHELL", "anvil --help || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    image: ghcr.io/foundry-rs/foundry:latest
    platform: linux/amd64
    ports:
      - "8545:8545"

  world_deployer:
    command: "--rpc-url http://anvil:8545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
    container_name: structuracontractus_world_deployer
    depends_on:
      anvil:
        condition: service_healthy
    image: ghcr.io/projectawakening/world-chain-deployer-image:0.0.17
    platform: linux/amd64
    tty: true
