name: "Release"

on:
  push:
    branches:
      - beta
      - main

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true # ensure only one release workflow runs per branch (e.g., "release-beta" or "release-main")

permissions:
  contents: write # to be able to publish a github release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

jobs:

  release_portae_astrales:
    name: "Release - @aetherisnova/portae-astrales"
    uses: ./.github/workflows/version_release.yml
    with:
      package_dir: "portae-astrales"
